### PR TITLE
Adjust development branch

### PR DESCRIPTION
**Pull request by jstastny-cz**
development branch is lacking many changes that were made only to 8.x because that was the "branch-to-get" right after apache transfer. After quarkus upgrade, development branch has effectively become the branch to use, but no one adjusted CI and the branch itself to map to what is actually needed (and was done in 8.x).

I am backporting in batch commits from 8.x (some adjusted to fit development branch config differences - jdks, etc).

### CODE REVIEW

**Review by lucamolteni — APPROVED** [review]

**Review by rodrigonull — APPROVED** [review]
LGTM. Thank you!

**Comment by jstastny-cz** [comment]
This is supposed to be squashed before merging.

**Comment by lucamolteni** [comment]
> This is supposed to be squashed before merging.

you sure? Isn't it clearer if we keep all commits separated?

**Comment by jstastny-cz** [comment]
> > This is supposed to be squashed before merging.
> 
> you sure? Isn't it clearer if we keep all commits separated?

Thing is that I've needed to cherry-pick the initial ASF transfer commit, which overwrote some partial adjustments that were in place, so I needed to cherry-pick those again (to keep my sanity here). So the commit history is not nice and clean - if that's not a blocker, we can keep commits separate.

**Comment by jstastny-cz** [comment]
There seems to be test failure, @lucamolteni have you seen such?
```
2024-07-25T13:15:04.0044929Z [INFO] --- failsafe:3.0.0-M8:integration-test (default) @ optaplanner-hello-world-school-timetabling-quickstart ---
2024-07-25T13:15:04.0510328Z [INFO] Failsafe report directory: /home/runner/work/incubator-kie-optaplanner-quickstarts/incubator-kie-optaplanner-quickstarts/apache_incubator-kie-optaplanner-quickstarts/hello-world/target/failsafe-reports
2024-07-25T13:15:04.0532050Z [INFO] Using auto detected provider org.apache.maven.surefire.junitplatform.JUnitPlatformProvider
2024-07-25T13:15:04.2267475Z [INFO] 
2024-07-25T13:15:04.2268117Z [INFO] -------------------------------------------------------
2024-07-25T13:15:04.2268520Z [INFO]  T E S T S
2024-07-25T13:15:04.2268861Z [INFO] -------------------------------------------------------
2024-07-25T13:15:04.4272101Z [ERROR] Error occurred during initialization of boot layer
2024-07-25T13:15:04.4296654Z [ERROR] java.lang.module.FindException: Module jakarta.xml.bind not found
```
and that's it, no more stacktrace.

**Comment by lucamolteni** [comment]
> There seems to be test failure, @lucamolteni have you seen such?
> 
> ```
> 2024-07-25T13:15:04.0044929Z [INFO] --- failsafe:3.0.0-M8:integration-test (default) @ optaplanner-hello-world-school-timetabling-quickstart ---
> 2024-07-25T13:15:04.0510328Z [INFO] Failsafe report directory: /home/runner/work/incubator-kie-optaplanner-quickstarts/incubator-kie-optaplanner-quickstarts/apache_incubator-kie-optaplanner-quickstarts/hello-world/target/failsafe-reports
> 2024-07-25T13:15:04.0532050Z [INFO] Using auto detected provider org.apache.maven.surefire.junitplatform.JUnitPlatformProvider
> 2024-07-25T13:15:04.2267475Z [INFO] 
> 2024-07-25T13:15:04.2268117Z [INFO] -------------------------------------------------------
> 2024-07-25T13:15:04.2268520Z [INFO]  T E S T S
> 2024-07-25T13:15:04.2268861Z [INFO] -------------------------------------------------------
> 2024-07-25T13:15:04.4272101Z [ERROR] Error occurred during initialization of boot layer
> 2024-07-25T13:15:04.4296654Z [ERROR] java.lang.module.FindException: Module jakarta.xml.bind not found
> ```
> 
> and that's it, no more stacktrace.

I've seen those yesterday, when I tried executing tests on my machine (and didn't succeed)

Apparently, QuickStarts were always executed like this

https://github.com/apache/incubator-kie-optaplanner/blob/8d206380f7e762c26294c18b74bcb72c5c8bd5ea/.ci/jenkins/Jenkinsfile.deploy#L181

```
      stage('Build Quickstarts') {
            steps {
                script {
                    configFileProvider([configFile(fileId: env.MAVEN_SETTINGS_CONFIG_FILE_ID, variable: 'MAVEN_SETTINGS_FILE')]){
                        getOptaplannerQuickstartsMavenCommand()
                                .withProperty('maven.test.failure.ignore', true)
                                .skipTests(params.SKIP_TESTS)
                                .withSettingsXmlFile(MAVEN_SETTINGS_FILE)
                                .run('clean install')
                    }
                }
```

So for whatever reasons, tests failure were skipped and errors ignored. I personally have never worked on optaplanner-quickstarts at all so I don't really know

**Comment by lucamolteni** [comment]
> > There seems to be test failure, @lucamolteni have you seen such?
> > ```
> > 2024-07-25T13:15:04.0044929Z [INFO] --- failsafe:3.0.0-M8:integration-test (default) @ optaplanner-hello-world-school-timetabling-quickstart ---
> > 2024-07-25T13:15:04.0510328Z [INFO] Failsafe report directory: /home/runner/work/incubator-kie-optaplanner-quickstarts/incubator-kie-optaplanner-quickstarts/apache_incubator-kie-optaplanner-quickstarts/hello-world/target/failsafe-reports
> > 2024-07-25T13:15:04.0532050Z [INFO] Using auto detected provider org.apache.maven.surefire.junitplatform.JUnitPlatformProvider
> > 2024-07-25T13:15:04.2267475Z [INFO] 
> > 2024-07-25T13:15:04.2268117Z [INFO] -------------------------------------------------------
> > 2024-07-25T13:15:04.2268520Z [INFO]  T E S T S
> > 2024-07-25T13:15:04.2268861Z [INFO] -------------------------------------------------------
> > 2024-07-25T13:15:04.4272101Z [ERROR] Error occurred during initialization of boot layer
> > 2024-07-25T13:15:04.4296654Z [ERROR] java.lang.module.FindException: Module jakarta.xml.bind not found
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and that's it, no more stacktrace.
> 
> I've seen those yesterday, when I tried executing tests on my machine (and didn't succeed)
> 
> Apparently, QuickStarts were always executed like this
> 
> https://github.com/apache/incubator-kie-optaplanner/blob/8d206380f7e762c26294c18b74bcb72c5c8bd5ea/.ci/jenkins/Jenkinsfile.deploy#L181
> 
> ```
>       stage('Build Quickstarts') {
>             steps {
>                 script {
>                     configFileProvider([configFile(fileId: env.MAVEN_SETTINGS_CONFIG_FILE_ID, variable: 'MAVEN_SETTINGS_FILE')]){
>                         getOptaplannerQuickstartsMavenCommand()
>                                 .withProperty('maven.test.failure.ignore', true)
>                                 .skipTests(params.SKIP_TESTS)
>                                 .withSettingsXmlFile(MAVEN_SETTINGS_FILE)
>                                 .run('clean install')
>                     }
>                 }
> ```
> 
> So for whatever reasons, tests failure were skipped and errors ignored. I personally have never worked on optaplanner-quickstarts at all so I don't really know

Anyway I found the fix see

https://github.com/apache/incubator-kie-optaplanner-quickstarts/pull/633

**Comment by lucamolteni** [comment]
I rebased the branch over the module system fix. 

The build is failing on 

```
2024-07-26T07:52:31.7821123Z [ERROR] Tests run: 3, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.416 s <<< FAILURE! - in org.acme.callcenter.solver.SolverServiceTest
2024-07-26T07:52:31.7823332Z [ERROR] org.acme.callcenter.solver.SolverServiceTest.removeCall  Time elapsed: 0.02 s  <<< FAILURE!
2024-07-26T07:52:31.7824733Z java.lang.AssertionError: 
2024-07-26T07:52:31.7826699Z 
2024-07-26T07:52:31.7827079Z Expecting RegularEnumSet:
2024-07-26T07:52:31.7827840Z   [ENGLISH, LIFE_INSURANCE, PROPERTY_INSURANCE]
2024-07-26T07:52:31.7828677Z to contain:
2024-07-26T07:52:31.7829403Z   [ENGLISH, CAR_INSURANCE]
2024-07-26T07:52:31.7830209Z but could not find the following element(s):
2024-07-26T07:52:31.7830830Z   [CAR_INSURANCE]
2024-07-26T07:52:31.7831125Z 
2024-07-26T07:52:31.7831744Z 	at org.acme.callcent
```


But after the fix the `development` branch runs fine with the tests on my machine

```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] optaplanner-hello-world-school-timetabling-quickstart 1.0-SNAPSHOT SUCCESS [ 10.404 s]
[INFO] optaplanner-spring-boot-school-timetabling-quickstart 1.0-SNAPSHOT SUCCESS [ 30.592 s]
[INFO] optaplanner-activemq-quarkus-school-timetabling 1.0-SNAPSHOT SUCCESS [  0.003 s]
[INFO] optaplanner-activemq-quarkus-school-timetabling-common 1.0-SNAPSHOT SUCCESS [  0.210 s]
[INFO] optaplanner-activemq-quarkus-school-timetabling-client 1.0-SNAPSHOT SUCCESS [  4.577 s]
[INFO] optaplanner-activemq-quarkus-school-timetabling-solver 1.0-SNAPSHOT SUCCESS [  6.078 s]
[INFO] optaplanner-kotlin-quarkus-school-timetabling-quickstart 1.0-SNAPSHOT SUCCESS [ 17.260 s]
[INFO] optaplanner-quarkus-school-timetabling-quickstart 1.0-SNAPSHOT SUCCESS [ 17.492 s]
[INFO] optaplanner-quarkus-facility-location-quickstart 1.0-SNAPSHOT SUCCESS [  4.819 s]
[INFO] optaplanner-quarkus-maintenance-scheduling-quickstart 1.0-SNAPSHOT SUCCESS [  7.159 s]
[INFO] optaplanner-quarkus-call-center-quickstart 1.0-SNAPSHOT SUCCESS [  4.565 s]
[INFO] optaplanner-quarkus-vaccination-scheduling-quickstart 1.0-SNAPSHOT SUCCESS [  5.993 s]
[INFO] optaplanner-quarkus-vehicle-routing-quickstart 1.0-SNAPSHOT SUCCESS [  5.506 s]
[INFO] optaplanner-quarkus-order-picking-quickstart 1.0-SNAPSHOT SUCCESS [  4.644 s]
[INFO] optaplanner-quarkus-employee-scheduling-quickstart 1.0-SNAPSHOT SUCCESS [  8.027 s]
[INFO] OptaPlanner Quickstarts 999-SNAPSHOT ............... SUCCESS [  1.132 s]
[INFO] OptaPlanner Quickstarts Showcase 999-SNAPSHOT ...... SUCCESS [  6.023 s]
[INFO] kubernetes-demo 1.0-SNAPSHOT ....................... SUCCESS [  0.003 s]
[INFO] kubernetes-demo-common 1.0-SNAPSHOT ................ SUCCESS [  1.875 s]
[INFO] kubernetes-demo-app 1.0-SNAPSHOT ................... SUCCESS [  6.655 s]
[INFO] kubernetes-demo-school-timetabling 1.0-SNAPSHOT .... SUCCESS [  6.451 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  02:29 min
[INFO] Finished at: 2024-07-26T10:14:21+02:00
[INFO] ------------------------------------------------------------------------
lmolteni@lmolteni-mac optaplanner-quickstarts %
```

So I'm still investigating

**Comment by lucamolteni** [comment]
@jstastny-cz all tests passing, merged

I guess we're now fine to retrigger the release

**Pull request merged**
