### PR TITLE
KOGITO-6962 DSL reorganization for flexibility

### PR DESCRIPTION
**Pull request by radtriste**
https://issues.redhat.com/browse/KOGITO-6962

Depends on https://github.com/kiegroup/kogito-pipelines/pull/416

### CODE REVIEW

**Comment by radtriste** [comment]
jenkins retest this

**Comment by radtriste** [comment]
jenkins retest this

**Comment by radtriste** [comment]
jenkins retest this

**Review by rsynek — APPROVED** [review]

**Comment by kie-ci1** [comment]
**(tests) - optaplanner-quickstarts job** `#2` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/custom/job/tradisso/job/kogito-6962/job/kogito-6962/job/pullrequest/job/optaplanner-quickstarts.tests.optaplanner-quickstarts/2/display/redirect or see console log:
<details>
<summary><b>Console Logs</b></summary>
GitHub pull request #322 of commit 5124fab12c10a74945ee1c5bef8308a796417891, no merge conflicts.<br/>Setting status of 5124fab12c10a74945ee1c5bef8308a796417891 to PENDING with url https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/custom/job/tradisso/job/kogito-6962/job/kogito-6962/job/pullrequest/job/optaplanner-quickstarts.tests.optaplanner-quickstarts/2/display/redirect and message: 'Build started.'<br/>Using context: (build) optaplanner-quickstarts<br/>Checking out git https://github.com/radtriste/kogito-pipelines.git into /var/lib/jenkins/jobs/custom/jobs/tradisso/jobs/kogito-6962/jobs/kogito-6962/jobs/pullrequest/jobs/optaplanner-quickstarts.tests.optaplanner-quickstarts/workspace@script to read .ci/jenkins/Jenkinsfile.buildchain<br/>The recommended git tool is: NONE<br/>using credential radtriste<br/> > git rev-parse --resolve-git-dir /var/lib/jenkins/jobs/custom/jobs/tradisso/jobs/kogito-6962/jobs/kogito-6962/jobs/pullrequest/jobs/optaplanner-quickstarts.tests.optaplanner-quickstarts/workspace@script/.git # timeout=10<br/>Fetching changes from the remote Git repository<br/> > git config remote.origin.url https://github.com/radtriste/kogito-pipelines.git # timeout=10<br/>Cleaning workspace<br/> > git rev-parse --verify HEAD # timeout=10<br/>Resetting working tree<br/> > git reset --hard # timeout=10<br/> > git clean -fdx # timeout=10<br/>Fetching upstream changes from https://github.com/radtriste/kogito-pipelines.git<br/> > git --version # timeout=10<br/> > git --version # 'git version 1.8.3.1'<br/>using GIT_ASKPASS to set credentials radtriste@gh<br/> > git fetch --tags --progress https://github.com/radtriste/kogito-pipelines.git +refs/heads/*:refs/remotes/origin/* # timeout=10<br/> > git rev-parse origin/kogito-6962^{commit} # timeout=10<br/>Checking out Revision 468d45e9abc19f9b3c9677f3a8990525876df5a4 (origin/kogito-6962)<br/> > git config core.sparsecheckout # timeout=10<br/> > git checkout -f 468d45e9abc19f9b3c9677f3a8990525876df5a4 # timeout=10<br/>Commit message: "KOGITO-6962 DSL reorganization for flexibility"<br/>First time build. Skipping changelog.<br/>Loading library jenkins-pipeline-shared-libraries@main<br/>Attempting to resolve main from remote references...<br/> > git --version # timeout=10<br/> > git --version # 'git version 1.8.3.1'<br/>using GIT_SSH to set credentials SSH: kie-ci service account with access to jboss-integration private github space<br/>[INFO] Currently running in a labeled security context<br/> > /usr/bin/chcon --type=ssh_home_t /tmp/jenkins-gitclient-ssh2218252922659845378.key<br/> > git ls-remote -h https://github.com/kiegroup/jenkins-pipeline-shared-libraries # timeout=10<br/>Found match: refs/heads/main revision 21afeeac35a851b46d694688c2562d914fab8e63<br/>The recommended git tool is: NONE<br/>using credential kie-ci-user-key<br/> > git rev-parse --resolve-git-dir /var/lib/jenkins/jobs/custom/jobs/tradisso/jobs/kogito-6962/jobs/kogito-6962/jobs/pullrequest/jobs/optaplanner-quickstarts.tests.optaplanner-quickstarts/workspace@libs/jenkins-pipeline-shared-libraries/.git # timeout=10<br/>Fetching changes from the remote Git repository<br/> > git config remote.origin.url https://github.com/kiegroup/jenkins-pipeline-shared-libraries # timeout=10<br/>Fetching without tags<br/>Fetching upstream changes from https://github.com/kiegroup/jenkins-pipeline-shared-libraries<br/> > git --version # timeout=10<br/> > git --version # 'git version 1.8.3.1'<br/>using GIT_SSH to set credentials SSH: kie-ci service account with access to jboss-integration private github space<br/>[INFO] Currently running in a labeled security context<br/> > /usr/bin/chcon --type=ssh_home_t /var/lib/jenkins/jobs/custom/jobs/tradisso/jobs/kogito-6962/jobs/kogito-6962/jobs/pullrequest/jobs/optaplanner-quickstarts.tests.optaplanner-quickstarts/workspace@libs/jenkins-pipeline-shared-libraries@tmp/jenkins-gitclient-ssh4885827923053025132.key<br/> > git fetch --no-tags --progress https://github.com/kiegroup/jenkins-pipeline-shared-libraries +refs/heads/*:refs/remotes/origin/* # timeout=10<br/>Checking out Revision 21afeeac35a851b46d694688c2562d914fab8e63 (main)<br/> > git config core.sparsecheckout # timeout=10<br/> > git checkout -f 21afeeac35a851b46d694688c2562d914fab8e63 # timeout=10<br/>Commit message: "pmebuild cleanScript (#188)"<br/> > git rev-list --no-walk 21afeeac35a851b46d694688c2562d914fab8e63 # timeout=10<br/>[Pipeline] Start of Pipeline<br/>[Pipeline] node<br/>Still waiting to schedule task<br/>Waiting for next available executor on ‘kie-rhel7&&kie-mem16g&&!master’<br/>Running on rhos-01-kie-psi-rhel7-xlarge-69 in /home/jenkins/workspace/custom/tradisso/kogito-6962/kogito-6962/pullrequest/optaplanner-quickstarts.tests.optaplanner-quickstarts<br/>[Pipeline] {<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Checkout SCM)<br/>[Pipeline] checkout<br/>The recommended git tool is: NONE<br/>using credential radtriste<br/>Cloning the remote Git repository<br/>Cloning repository https://github.com/radtriste/kogito-pipelines.git<br/>Avoid second fetch<br/>Checking out Revision 468d45e9abc19f9b3c9677f3a8990525876df5a4 (origin/kogito-6962)<br/> > git init /home/jenkins/workspace/custom/tradisso/kogito-6962/kogito-6962/pullrequest/optaplanner-quickstarts.tests.optaplanner-quickstarts # timeout=10<br/>Fetching upstream changes from https://github.com/radtriste/kogito-pipelines.git<br/> > git --version # timeout=10<br/> > git --version # 'git version 2.34.1'<br/>using GIT_ASKPASS to set credentials radtriste@gh<br/> > git fetch --tags --force --progress -- https://github.com/radtriste/kogito-pipelines.git +refs/heads/*:refs/remotes/origin/* # timeout=10<br/> > git config remote.origin.url https://github.com/radtriste/kogito-pipelines.git # timeout=10<br/> > git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10<br/> > git rev-parse origin/kogito-6962^{commit} # timeout=10<br/> > git config core.sparsecheckout # timeout=10<br/> > git checkout -f 468d45e9abc19f9b3c9677f3a8990525876df5a4 # timeout=10<br/>Commit message: "KOGITO-6962 DSL reorganization for flexibility"<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] timestamps<br/>[Pipeline] {<br/>[Pipeline] timeout<br/>[2022-04-28T08:57:53.286Z] Timeout set to expire in 3 hr 0 min<br/>[Pipeline] {<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Tool Install)<br/>[Pipeline] tool<br/>[2022-04-28T08:57:54.385Z] Unpacking https://nodejs.org/dist/v12.16.3/node-v12.16.3-linux-x64.tar.gz to /home/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/nodejs-12.16.3 on rhos-01-kie-psi-rhel7-xlarge-69<br/>[Pipeline] envVarsForTool<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] stage<br/>[Pipeline] { (Initialize)<br/>[Pipeline] tool<br/>[Pipeline] envVarsForTool<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>[2022-04-28T08:58:03.683Z] + printenv<br/>[Pipeline] archiveArtifacts<br/>[2022-04-28T08:58:04.184Z] Archiving artifacts<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // withEnv<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (check space before build)<br/>[Pipeline] tool<br/>[Pipeline] envVarsForTool<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] dir<br/>[2022-04-28T08:58:08.996Z] Running in /home/jenkins/workspace/custom/tradisso/kogito-6962/kogito-6962/pullrequest/optaplanner-quickstarts.tests.optaplanner-quickstarts<br/>[Pipeline] {<br/>[Pipeline] echo<br/>[2022-04-28T08:58:09.280Z] [INFO] space left on the machine<br/>[Pipeline] sh<br/>[2022-04-28T08:58:09.980Z] + df -h<br/>[2022-04-28T08:58:09.981Z] Filesystem      Size  Used Avail Use% Mounted on<br/>[2022-04-28T08:58:09.981Z] devtmpfs        7.8G     0  7.8G   0% /dev<br/>[2022-04-28T08:58:09.981Z] tmpfs           7.8G     0  7.8G   0% /dev/shm<br/>[2022-04-28T08:58:09.981Z] tmpfs           7.8G   17M  7.8G   1% /run<br/>[2022-04-28T08:58:09.981Z] tmpfs           7.8G     0  7.8G   0% /sys/fs/cgroup<br/>[2022-04-28T08:58:09.981Z] /dev/vda1        80G   18G   63G  23% /<br/>[2022-04-28T08:58:09.981Z] tmpfs           1.6G     0  1.6G   0% /run/user/1000<br/>[Pipeline] echo<br/>[2022-04-28T08:58:10.185Z] [INFO] space of /home/jenkins<br/>[Pipeline] sh<br/>[2022-04-28T08:58:11.080Z] + du -h -d1 /home/jenkins<br/>[2022-04-28T08:58:11.083Z] 4.0K	/home/jenkins/.ssh<br/>[2022-04-28T08:58:11.083Z] 0	/home/jenkins/go<br/>[2022-04-28T08:58:11.083Z] 8.0K	/home/jenkins/.vnc<br/>[2022-04-28T08:58:11.083Z] 8.0K	/home/jenkins/.m2<br/>[2022-04-28T08:58:11.083Z] 2.1G	/home/jenkins/git-repos<br/>[2022-04-28T08:58:11.083Z] 8.0K	/home/jenkins/.config<br/>[2022-04-28T08:58:11.083Z] 4.0K	/home/jenkins/.cekit<br/>[2022-04-28T08:58:11.083Z] 80M	/home/jenkins/virtenvs<br/>[2022-04-28T08:58:11.083Z] 30M	/home/jenkins/remoting<br/>[2022-04-28T08:58:11.083Z] 0	/home/jenkins/.cache<br/>[2022-04-28T08:58:11.083Z] 2.3M	/home/jenkins/workspace<br/>[2022-04-28T08:58:11.083Z] 0	/home/jenkins/.pki<br/>[2022-04-28T08:58:11.083Z] 81M	/home/jenkins/tools<br/>[2022-04-28T08:58:11.083Z] 0	/home/jenkins/caches<br/>[2022-04-28T08:58:11.083Z] 2.3G	/home/jenkins<br/>[Pipeline] echo<br/>[2022-04-28T08:58:11.784Z] [INFO] space of workspace<br/>[Pipeline] sh<br/>[2022-04-28T08:58:13.280Z] + du -h -d3 /home/jenkins/workspace<br/>[2022-04-28T08:58:13.281Z] 2.3M	/home/jenkins/workspace/custom/tradisso/kogito-6962<br/>[2022-04-28T08:58:13.281Z] 2.3M	/home/jenkins/workspace/custom/tradisso<br/>[2022-04-28T08:58:13.281Z] 2.3M	/home/jenkins/workspace/custom<br/>[2022-04-28T08:58:13.281Z] 2.3M	/home/jenkins/workspace<br/>[Pipeline] }<br/>[Pipeline] // dir<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // withEnv<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Install build-chain tool)<br/>[Pipeline] tool<br/>[Pipeline] envVarsForTool<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] echo<br/>[2022-04-28T08:58:16.484Z] [INFO] Getting build-chain version from composite action file<br/>[Pipeline] readFile<br/>[Pipeline] echo<br/>[2022-04-28T08:58:17.083Z] [INFO] build-chain version recovered '2.3.34'<br/>[Pipeline] sh<br/>[2022-04-28T08:58:17.785Z] + npm install -g @kie/build-chain-action@2.3.34 -registry=https://repository.engineering.redhat.com/nexus/repository/registry.npmjs.org/<br/>[2022-04-28T08:58:20.684Z] /home/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/nodejs-12.16.3/bin/build-chain-action -> /home/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/nodejs-12.16.3/lib/node_modules/@kie/build-chain-action/bin/build-chain-cli.js<br/>[2022-04-28T08:58:20.684Z] npm WARN notsup Unsupported engine for @kie/build-chain-action@2.3.34: wanted: {"node":">= 12.18.0"} (current: {"node":"12.16.3","npm":"6.14.4"})<br/>[2022-04-28T08:58:20.684Z] npm WARN notsup Not compatible with your version of node/npm: @kie/build-chain-action@2.3.34<br/>[2022-04-28T08:58:20.684Z] npm WARN @octokit/plugin-request-log@1.0.4 requires a peer of @octokit/core@>=3 but none is installed. You must install peer dependencies yourself.<br/>[2022-04-28T08:58:20.684Z] <br/>[2022-04-28T08:58:20.684Z] + @kie/build-chain-action@2.3.34<br/>[2022-04-28T08:58:20.684Z] added 108 packages from 88 contributors in 2.727s<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // withEnv<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Build projects)<br/>[Pipeline] tool<br/>[Pipeline] envVarsForTool<br/>[Pipeline] tool<br/>[Pipeline] envVarsForTool<br/>[Pipeline] tool<br/>[Pipeline] envVarsForTool<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] echo<br/>[2022-04-28T08:58:24.082Z] BUILD_MVN_OPTS_CURRENT = -Dfull<br/>[Pipeline] configFileProvider<br/>[2022-04-28T08:58:24.185Z] provisioning config files...<br/>[2022-04-28T08:58:24.192Z] copy managed file [kogito_pr_settings] to file:/home/jenkins/workspace/custom/tradisso/kogito-6962/kogito-6962/pullrequest/optaplanner-quickstarts.tests.optaplanner-quickstarts@tmp/config3124344145009690002tmp<br/>[Pipeline] {<br/>[Pipeline] withCredentials<br/>[2022-04-28T08:58:24.485Z] Masking supported pattern matches of $GITHUB_TOKEN<br/>[Pipeline] {<br/>[Pipeline] sh<br/>[2022-04-28T08:58:24.791Z] Warning: A secret was passed to "sh" using Groovy String interpolation, which is insecure.<br/>[2022-04-28T08:58:24.792Z] 		 Affected argument(s) used the following variable(s): [GITHUB_TOKEN]<br/>[2022-04-28T08:58:24.792Z] 		 See https://jenkins.io/redirect/groovy-string-interpolation for details.<br/>[2022-04-28T08:58:25.784Z] + build-chain-action -token=**** -df=https://raw.githubusercontent.com/kiegroup/kogito-pipelines/kogito-6962/.ci/pull-request-config.yaml -folder=bc build pr -url=https://github.com/kiegroup/optaplanner-quickstarts/pull/322 -sp=kiegroup/optaplanner-quickstarts --skipParallelCheckout -cct '(^mvn .*)||$1 -s /home/jenkins/workspace/custom/tradisso/kogito-6962/kogito-6962/pullrequest/optaplanner-quickstarts.tests.optaplanner-quickstarts@tmp/config3124344145009690002tmp -Dmaven.wagon.http.ssl.insecure=true -Dmaven.test.failure.ignore=true'<br/>[2022-04-28T08:58:26.084Z] [INFO]  Executing pull request flow for https://github.com/kiegroup/optaplanner-quickstarts/pull/322 in bc<br/>[2022-04-28T08:58:26.384Z] [INFO]  https://raw.githubusercontent.com/kiegroup/kogito-pipelines/kogito-6962/.ci/pull-request-config.yaml exists, using it<br/>[2022-04-28T08:58:26.384Z] [ERROR]  Error getting https://raw.githubusercontent.com/kiegroup/kogito-pipelines/kogito-6962/.ci/pull-request-config.yaml. Error: Status: 404. Not Found<br/>[Pipeline] }<br/>[Pipeline] // withCredentials<br/>[Pipeline] }<br/>[2022-04-28T08:58:26.904Z] Deleting 1 temporary files<br/>[Pipeline] // configFileProvider<br/>[Pipeline] }<br/>[Pipeline] // script<br/>Post stage<br/>[Pipeline] junit<br/>[2022-04-28T08:58:27.491Z] Recording test results<br/>[2022-04-28T08:58:28.095Z] No test report files were found. Configuration error?<br/>Error when executing always post condition:<br/>Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to rhos-01-kie-psi-rhel7-xlarge-69<br/>		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1797)<br/>		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:356)<br/>		at hudson.remoting.Channel.call(Channel.java:1001)<br/>		at hudson.FilePath.act(FilePath.java:1166)<br/>		at hudson.FilePath.act(FilePath.java:1155)<br/>		at hudson.tasks.junit.JUnitParser.parseResult(JUnitParser.java:107)<br/>		at hudson.tasks.junit.JUnitResultArchiver.parse(JUnitResultArchiver.java:153)<br/>		at hudson.tasks.junit.JUnitResultArchiver.parseAndSummarize(JUnitResultArchiver.java:247)<br/>		at hudson.tasks.junit.pipeline.JUnitResultsStepExecution.run(JUnitResultsStepExecution.java:63)<br/>		at hudson.tasks.junit.pipeline.JUnitResultsStepExecution.run(JUnitResultsStepExecution.java:29)<br/>		at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)<br/>		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)<br/>		at java.util.concurrent.FutureTask.run(FutureTask.java:266)<br/>		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)<br/>		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)<br/>		at java.lang.Thread.run(Thread.java:748)<br/>hudson.AbortException: No test report files were found. Configuration error?<br/>	at hudson.tasks.junit.JUnitParser$ParseResultCallable.invoke(JUnitParser.java:154)<br/>	at hudson.FilePath$FileCallableWrapper.call(FilePath.java:3338)<br/>	at hudson.remoting.UserRequest.perform(UserRequest.java:211)<br/>	at hudson.remoting.UserRequest.perform(UserRequest.java:54)<br/>	at hudson.remoting.Request$2.run(Request.java:376)<br/>	at hudson.remoting.InterceptingExecutorService.lambda$wrap$0(InterceptingExecutorService.java:78)<br/>	at java.util.concurrent.FutureTask.run(FutureTask.java:266)<br/>	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)<br/>	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)<br/>	at java.lang.Thread.run(Thread.java:750)<br/><br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>[2022-04-28T08:58:29.480Z] + rm -rf console.log<br/>[Pipeline] sh<br/>
</details>

**Comment by radtriste** [comment]
jenkins retest this

**Pull request merged**
