### PR TITLE
Remove workaround quarkus12458

### PR DESCRIPTION
**Pull request by ge0ffrey**

### CODE REVIEW

**Comment by triceo** [comment]
jenkins run native

**Review by rsynek — APPROVED** [review]

**Comment by rsynek** [comment]
Good to merge when the CI is green.

**Comment by ge0ffrey** [comment]
@Ginxo CI is failing with this error message. Might you know what that means?
```
[INFO]  [kiegroup/optaplanner-quickstarts] Merging https://github.com/kiegroup/optaplanner-quickstarts:stable into https://github.com/ge0ffrey/optaplanner-quickstarts:removeWorkaroundQuarkus12458
  Error:   command git pull https://github.com/ge0ffrey/optaplanner-quickstarts removeWorkaroundQuarkus12458 failed with code 1. Error Message: From https://github.com/ge0ffrey/optaplanner-quickstarts
```

**Comment by Ginxo** [comment]
> @Ginxo CI is failing with this error message. Might you know what that means?
> 
> ```
> [INFO]  [kiegroup/optaplanner-quickstarts] Merging https://github.com/kiegroup/optaplanner-quickstarts:stable into https://github.com/ge0ffrey/optaplanner-quickstarts:removeWorkaroundQuarkus12458
>   Error:   command git pull https://github.com/ge0ffrey/optaplanner-quickstarts removeWorkaroundQuarkus12458 failed with code 1. Error Message: From https://github.com/ge0ffrey/optaplanner-quickstarts
> ```

@ge0ffrey thanks for reporting it. Issue open https://github.com/kiegroup/github-action-build-chain/issues/153
I expect to have it soon, I let you know as soon as it is fixed

**Comment by Ginxo** [comment]
@ge0ffrey solved by `v2.5.8`

**Comment by ge0ffrey** [comment]
Thanks @Ginxo !

**Pull request merged**
