### PR TITLE
Lambda Memory Leak

### PR DESCRIPTION
**Pull request by teejae**
Only changed `@PlanningID` Field->Method, and now leaks classes
```sh
# Run hello world (loops every second)
$ optaplanner-quickstarts/hello-world/run.sh

# Show loaded classes being loaded every second
$ tail -f loadedClasses.txt
```

```
$ tail -f loadedClasses.txt
[1.066s][info][class,load] org.optaplanner.core.impl.localsearch.scope.LocalSearchMoveScope source: file:/Users/teejae/.m2/repository/org/optaplanner/optaplanner-core-impl/8.35.0-SNAPSHOT/optaplanner-core-impl-8.35.0-SNAPSHOT.jar
[1.066s][info][class,load] org.optaplanner.core.impl.localsearch.decider.LocalSearchDecider$$Lambda$636/0x000000080044a320 source: org.optaplanner.core.impl.localsearch.decider.LocalSearchDecider
[1.066s][info][class,load] org.optaplanner.core.impl.localsearch.decider.forager.AcceptedLocalSearchForager$1 source: file:/Users/teejae/.m2/repository/org/optaplanner/optaplanner-core-impl/8.35.0-SNAPSHOT/optaplanner-core-impl-8.35.0-SNAPSHOT.jar
[1.411s][info][class,load] java.io.ObjectInput source: jrt:/java.base
[1.411s][info][class,load] org.drools.core.marshalling.MarshallerReaderContext source: file:/Users/teejae/.gradle/caches/modules-2/files-2.1/org.drools/drools-core/8.34.0.Final/78ac6d7b2d92ae42928be281e4ba0a652384c831/drools-core-8.34.0.Final.jar
[5.938s][info][class,load] io.micrometer.core.instrument.composite.CompositeLongTaskTimer$CompositeSample$$Lambda$637/0x000000080044a960 source: io.micrometer.core.instrument.composite.CompositeLongTaskTimer$CompositeSample
[5.939s][info][class,load] io.micrometer.core.instrument.composite.CompositeLongTaskTimer$CompositeSample$$Lambda$638/0x000000080044ab90 source: io.micrometer.core.instrument.composite.CompositeLongTaskTimer$CompositeSample
[5.939s][info][class,load] io.micrometer.core.instrument.composite.CompositeMeterRegistry$$Lambda$639/0x000000080044add8 source: io.micrometer.core.instrument.composite.CompositeMeterRegistry
[5.939s][info][class,load] io.micrometer.core.instrument.composite.CompositeMeterRegistry$$Lambda$640/0x000000080044b000 source: io.micrometer.core.instrument.composite.CompositeMeterRegistry
[5.939s][info][class,load] org.optaplanner.core.impl.solver.DefaultSolver$$Lambda$641/0x000000080044b238 source: org.optaplanner.core.impl.solver.DefaultSolver
[6.950s][info][class,load] org.optaplanner.core.impl.domain.common.accessor.LambdaBeanPropertyMemberAccessor$$Lambda$642/0x000000080044b470 source: org.optaplanner.core.impl.domain.common.accessor.LambdaBeanPropertyMemberAccessor
[6.951s][info][class,load] org.optaplanner.core.impl.domain.common.accessor.LambdaBeanPropertyMemberAccessor$$Lambda$643/0x000000080044b6b0 source: org.optaplanner.core.impl.domain.common.accessor.LambdaBeanPropertyMemberAccessor
[6.952s][info][class,load] org.optaplanner.core.impl.domain.common.accessor.LambdaBeanPropertyMemberAccessor$$Lambda$644/0x000000080044b8f0 source: org.optaplanner.core.impl.domain.common.accessor.LambdaBeanPropertyMemberAccessor
[6.952s][info][class,load] org.optaplanner.core.impl.domain.common.accessor.LambdaBeanPropertyMemberAccessor$$Lambda$645/0x000000080044bb30 source: org.optaplanner.core.impl.domain.common.accessor.LambdaBeanPropertyMemberAccessor
[7.060s][info][class,load] org.drools.ancompiler.Compiledorg_acme_schooltimetabling_domain_LessonNetwork31008790748 source: __JVM_DefineClass__
[7.061s][info][class,load] org.optaplanner.core.impl.domain.common.accessor.LambdaBeanPropertyMemberAccessor$$Lambda$646/0x000000080044bd70 source: org.optaplanner.core.impl.domain.common.accessor.LambdaBeanPropertyMemberAccessor
[7.062s][info][class,load] org.optaplanner.core.impl.domain.common.accessor.LambdaBeanPropertyMemberAccessor$$Lambda$647/0x000000080044e000 source: org.optaplanner.core.impl.domain.common.accessor.LambdaBeanPropertyMemberAccessor
[7.074s][info][class,load] jdk.internal.reflect.GeneratedConstructorAccessor2 source: __ClassDefiner__
[13.066s][info][class,load] org.optaplanner.core.impl.domain.common.accessor.LambdaBeanPropertyMemberAccessor$$Lambda$648/0x000000080044e240 source: org.optaplanner.core.impl.domain.common.accessor.LambdaBeanPropertyMemberAccessor
[13.066s][info][class,load] org.optaplanner.core.impl.domain.common.accessor.LambdaBeanPropertyMemberAccessor$$Lambda$649/0x000000080044e480 source: org.optaplanner.core.impl.domain.common.accessor.LambdaBeanPropertyMemberAccessor
[13.067s][info][class,load] org.optaplanner.core.impl.domain.common.accessor.LambdaBeanPropertyMemberAccessor$$Lambda$650/0x000000080044e6c0 source: org.optaplanner.core.impl.domain.common.accessor.LambdaBeanPropertyMemberAccessor
[13.067s][info][class,load] org.optaplanner.core.impl.domain.common.accessor.LambdaBeanPropertyMemberAccessor$$Lambda$651/0x000000080044e900 source: org.optaplanner.core.impl.domain.common.accessor.LambdaBeanPropertyMemberAccessor
[13.087s][info][class,load] jdk.internal.reflect.GeneratedConstructorAccessor3 source: __ClassDefiner__
[13.173s][info][class,load] org.drools.ancompiler.Compiledorg_acme_schooltimetabling_domain_LessonNetwork31008790748 source: __JVM_DefineClass__
[13.174s][info][class,load] org.optaplanner.core.impl.domain.common.accessor.LambdaBeanPropertyMemberAccessor$$Lambda$652/0x000000080044eb40 source: org.optaplanner.core.impl.domain.common.accessor.LambdaBeanPropertyMemberAccessor
[13.174s][info][class,load] org.optaplanner.core.impl.domain.common.accessor.LambdaBeanPropertyMemberAccessor$$Lambda$653/0x000000080044ed80 source: org.optaplanner.core.impl.domain.common.accessor.LambdaBeanPropertyMemberAccessor
```

### Referenced pull requests

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

- for <b>pull request checks</b>  
  Please add comment: <b>Jenkins retest this</b>

- for a <b>specific pull request check</b>  
  please add comment: <b>Jenkins (re)run [optaplanner-quickstarts] tests</b>

- for a <b>full downstream build</b>  
  please add the label `run_fdb`

- for <b>quarkus branch checks</b>  
  Run checks against Quarkus current used branch  
  Please add comment: <b>Jenkins run quarkus-branch</b>

- for a <b>quarkus branch specific check</b>  
  Run checks against Quarkus current used branch  
  Please add comment: <b>Jenkins (re)run [optaplanner-quickstarts] quarkus-branch</b>

- for <b>quarkus main checks</b>  
  Run checks against Quarkus main branch  
  Please add comment: <b>Jenkins run quarkus-main</b>

- for a <b>specific quarkus main check</b>  
  Run checks against Quarkus main branch  
  Please add comment: <b>Jenkins (re)run [optaplanner-quickstarts] quarkus-branch</b>

- for <b>quarkus lts checks</b>  
  Run checks against Quarkus lts branch  
  Please add comment: <b>Jenkins run quarkus-lts</b>

- for a <b>specific quarkus lts check</b>  
  Run checks against Quarkus lts branch  
  Please add comment: <b>Jenkins (re)run [optaplanner-quickstarts] quarkus-lts</b>

- for <b>native checks</b>  
  Run native checks  
  Please add comment: <b>Jenkins run native</b>

- for a <b>specific native check</b>  
  Run native checks 
  Please add comment: <b>Jenkins (re)run [optaplanner-quickstarts] native</b>

- for <b>mandrel checks</b>  
  Run native checks against Mandrel image
  Please add comment: <b>Jenkins run mandrel</b>

- for a <b>specific mandrel check</b>  
  Run native checks against Mandrel image  
  Please add comment: <b>Jenkins (re)run [optaplanner-quickstarts] mandrel</b>

- for <b>mandrel lts checks</b>  
  Run native checks against Mandrel image and quarkus lts branch
  Please add comment: <b>Jenkins run mandrel-lts</b>

- for a <b>specific mandrel lts check</b>  
  Run native checks against Mandrel image and quarkus lts branch
  Please add comment: <b>Jenkins (re)run [optaplanner-quickstarts] mandrel-lts</b>
</details>

<details>
<summary>
How to backport a pull request to a different branch?
</summary>

In order to automatically create a **backporting pull request** please add one or more labels having the following format `backport-<branch-name>`, where `<branch-name>` is the name of the branch where the pull request must be backported to (e.g., `backport-7.67.x` to backport the original PR to the `7.67.x` branch).

> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main one) to another one, which is generally referring to a still maintained release branch. Keeping it simple: it is about to move a specific change or a set of them from one branch to another.

Once the original pull request is successfully merged, the automated action will create one backporting pull request per each label (with the previous format) that has been added.

If something goes wrong, the author will be notified and at this point a manual backporting is needed.

> **NOTE**: this automated backporting is triggered whenever a pull request on `main` branch is labeled or closed, but both conditions must be satisfied to get the new PR created.
</details>

### CODE REVIEW

**Comment by triceo** [comment]
ok to test

**Comment by triceo** [comment]
Thank you for taking the time to investigate this, @teejae! I'll look into it, hopefully next week already.
(And sorry for the botspam.)

**Comment by kie-ci3** [comment]
**(tests) - optaplanner-quickstarts job** `#123` was: **UNSTABLE**
Possible explanation: This should be test failures

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/optaplanner/job/main/job/pullrequest/job/optaplanner-quickstarts.tests.optaplanner-quickstarts/123/display/redirect

**Test results:**
- PASSED: 161
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/optaplanner/job/main/job/pullrequest/job/optaplanner-quickstarts.tests.optaplanner-quickstarts/123/testReport/org.acme.schooltimetabling/JarWithDependenciesIT/runJarWithDependencies/">org.acme.schooltimetabling.JarWithDependenciesIT.runJarWithDependencies</a></summary>
Executable JAR timed out.
</details>

**Comment by kie-ci3** [comment]
**(tests) - optaplanner-quickstarts job** `#124` was: **UNSTABLE**
Possible explanation: This should be test failures

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/optaplanner/job/main/job/pullrequest/job/optaplanner-quickstarts.tests.optaplanner-quickstarts/124/display/redirect

**Test results:**
- PASSED: 161
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/optaplanner/job/main/job/pullrequest/job/optaplanner-quickstarts.tests.optaplanner-quickstarts/124/testReport/org.acme.schooltimetabling/JarWithDependenciesIT/runJarWithDependencies/">org.acme.schooltimetabling.JarWithDependenciesIT.runJarWithDependencies</a></summary>
Executable JAR timed out.
</details>

**Pull request closed without merging**
