### PR TITLE
[8.11.x] Parametrize the optaplanner-bom

### PR DESCRIPTION
**Pull request by rsynek**
In order to test the right platform BOMs, the `org.optaplanner:optaplanner-bom` cannot be hardcoded in the quickstarts. It must be replaceable, although, by default, the quickstarts still depend on it.

When used with Quarkus platform, every quickstart based on Quarkus should import these two BOMs:
- `io.quarkus.platform:quarkus-bom`
- `io.quarkus.platform:quarkus-optaplanner-bom` -- contains just OptaPlanner and its dependencies **without** Quarkus.

@AntStephenson This PR will likely require rebuilding (the zip containing quickstarts).

### Referenced pull requests

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* for a <b>pull request build</b> please add comment: <b>Jenkins retest this</b>
* for a <b>full downstream build</b> please add the label `run_fdb`
* for a <b>specific pull request build</b> please add comment: <b>Jenkins (re)run [optaplanner-quickstarts] tests</b>
* for a <b>Quarkus LTS check</b> please add comment: <b>Jenkins run LTS</b>
* for a <b>specific Quarkus LTS check</b> please add comment: <b>Jenkins (re)run [optaplanner-quickstarts] LTS</b>
* for a <b>Native check</b> please add comment: <b>Jenkins run native</b>
* for a <b>specific Native LTS check</b> please add comment: <b>Jenkins (re)run [optaplanner-quickstarts] native</b>
</details>

### CODE REVIEW

**Review by jstastny-cz — APPROVED** [review]
Looks good to me, thank you.

**Review by antncl — APPROVED** [review]

**Review by ge0ffrey — APPROVED** [review]

**Comment by rsynek** [comment]
jenkins retest this

**Comment by rsynek** [comment]
The Jenkins build fails due to a broken Jenkins build chain in `1.11.x`. Hopefully, this PR https://github.com/kiegroup/kogito-pipelines/pull/376 will fix that.

**Comment by rsynek** [comment]
jenkins retest this

**Comment by kie-ci1** [comment]
**(tests) - null job** #8 was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/1.11.x/job/pullrequest/job/optaplanner-quickstarts.tests.optaplanner-quickstarts/8/display/redirect or see console log:
<details>
<summary><b>Console Logs</b></summary>
GitHub pull request #273 of commit 866274fa3b46c6ba1a61e73b54ca959a6a97aedb, no merge conflicts.<br/>Setting status of 866274fa3b46c6ba1a61e73b54ca959a6a97aedb to PENDING with url https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/1.11.x/job/pullrequest/job/optaplanner-quickstarts.tests.optaplanner-quickstarts/8/display/redirect and message: 'Build started.'<br/>Using context: (build) optaplanner-quickstarts<br/>Checking out git https://github.com/kiegroup/kogito-pipelines.git into /var/lib/jenkins/jobs/KIE/jobs/kogito/jobs/1.11.x/jobs/pullrequest/jobs/optaplanner-quickstarts.tests.optaplanner-quickstarts/workspace@script to read .ci/jenkins/Jenkinsfile.buildchain<br/>The recommended git tool is: NONE<br/>using credential kie-ci<br/> > git rev-parse --resolve-git-dir /var/lib/jenkins/jobs/KIE/jobs/kogito/jobs/1.11.x/jobs/pullrequest/jobs/optaplanner-quickstarts.tests.optaplanner-quickstarts/workspace@script/.git # timeout=10<br/>Fetching changes from the remote Git repository<br/> > git config remote.origin.url https://github.com/kiegroup/kogito-pipelines.git # timeout=10<br/>Cleaning workspace<br/> > git rev-parse --verify HEAD # timeout=10<br/>Resetting working tree<br/> > git reset --hard # timeout=10<br/> > git clean -fdx # timeout=10<br/>Fetching upstream changes from https://github.com/kiegroup/kogito-pipelines.git<br/> > git --version # timeout=10<br/> > git --version # 'git version 1.8.3.1'<br/>using GIT_ASKPASS to set credentials PSSWD: kie-ci service account with access to jboss-integration private github space<br/> > git fetch --tags --progress https://github.com/kiegroup/kogito-pipelines.git +refs/heads/*:refs/remotes/origin/* # timeout=10<br/> > git rev-parse origin/1.11.x^{commit} # timeout=10<br/>Checking out Revision 79c52638b8f16061c2e093dc24ecc025eebf0950 (origin/1.11.x)<br/> > git config core.sparsecheckout # timeout=10<br/> > git checkout -f 79c52638b8f16061c2e093dc24ecc025eebf0950 # timeout=10<br/>Commit message: "Fix the Jenkins buildchain (#376)"<br/> > git rev-list --no-walk 8a4cbc283e5a514921cf7f799284413f36136096 # timeout=10<br/>Loading library jenkins-pipeline-shared-libraries@main<br/>Attempting to resolve main from remote references...<br/> > git --version # timeout=10<br/> > git --version # 'git version 1.8.3.1'<br/>using GIT_SSH to set credentials SSH: kie-ci service account with access to jboss-integration private github space<br/>[INFO] Currently running in a labeled security context<br/> > /usr/bin/chcon --type=ssh_home_t /tmp/jenkins-gitclient-ssh6381227704315751540.key<br/> > git ls-remote -h https://github.com/kiegroup/jenkins-pipeline-shared-libraries # timeout=10<br/>Found match: refs/heads/main revision a6d8872fc1ee696e346aac853dd25cae7c2749c5<br/>The recommended git tool is: NONE<br/>using credential kie-ci-user-key<br/> > git rev-parse --resolve-git-dir /var/lib/jenkins/jobs/KIE/jobs/kogito/jobs/1.11.x/jobs/pullrequest/jobs/optaplanner-quickstarts.tests.optaplanner-quickstarts/workspace@libs/jenkins-pipeline-shared-libraries/.git # timeout=10<br/>Fetching changes from the remote Git repository<br/> > git config remote.origin.url https://github.com/kiegroup/jenkins-pipeline-shared-libraries # timeout=10<br/>Fetching without tags<br/>Fetching upstream changes from https://github.com/kiegroup/jenkins-pipeline-shared-libraries<br/> > git --version # timeout=10<br/> > git --version # 'git version 1.8.3.1'<br/>using GIT_SSH to set credentials SSH: kie-ci service account with access to jboss-integration private github space<br/>[INFO] Currently running in a labeled security context<br/> > /usr/bin/chcon --type=ssh_home_t /var/lib/jenkins/jobs/KIE/jobs/kogito/jobs/1.11.x/jobs/pullrequest/jobs/optaplanner-quickstarts.tests.optaplanner-quickstarts/workspace@libs/jenkins-pipeline-shared-libraries@tmp/jenkins-gitclient-ssh5745919951373276976.key<br/> > git fetch --no-tags --progress https://github.com/kiegroup/jenkins-pipeline-shared-libraries +refs/heads/*:refs/remotes/origin/* # timeout=10<br/>Checking out Revision a6d8872fc1ee696e346aac853dd25cae7c2749c5 (main)<br/> > git config core.sparsecheckout # timeout=10<br/> > git checkout -f a6d8872fc1ee696e346aac853dd25cae7c2749c5 # timeout=10<br/>Commit message: "Update logs markdown on GH to hide default (#186)"<br/> > git rev-list --no-walk 73169aa1ceff142b4609f0fce796ea29ccf633e7 # timeout=10<br/>[Pipeline] Start of Pipeline<br/>[Pipeline] node<br/>Still waiting to schedule task<br/>Waiting for next available executor on ‘kie-rhel7&&kie-mem16g&&!master’<br/>Running on rhos-d-kie-rhel7-xlarge-196 in /home/jenkins/workspace/KIE/kogito/1.11.x/pullrequest/optaplanner-quickstarts.tests.optaplanner-quickstarts<br/>[Pipeline] {<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Checkout SCM)<br/>[Pipeline] checkout<br/>The recommended git tool is: NONE<br/>using credential kie-ci<br/>Cloning the remote Git repository<br/>Cloning repository https://github.com/kiegroup/kogito-pipelines.git<br/> > git init /home/jenkins/workspace/KIE/kogito/1.11.x/pullrequest/optaplanner-quickstarts.tests.optaplanner-quickstarts # timeout=10<br/>Fetching upstream changes from https://github.com/kiegroup/kogito-pipelines.git<br/> > git --version # timeout=10<br/> > git --version # 'git version 2.34.1'<br/>using GIT_ASKPASS to set credentials PSSWD: kie-ci service account with access to jboss-integration private github space<br/> > git fetch --tags --force --progress -- https://github.com/kiegroup/kogito-pipelines.git +refs/heads/*:refs/remotes/origin/* # timeout=10<br/>Avoid second fetch<br/>Checking out Revision 79c52638b8f16061c2e093dc24ecc025eebf0950 (origin/1.11.x)<br/> > git config remote.origin.url https://github.com/kiegroup/kogito-pipelines.git # timeout=10<br/> > git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10<br/> > git rev-parse origin/1.11.x^{commit} # timeout=10<br/> > git config core.sparsecheckout # timeout=10<br/> > git checkout -f 79c52638b8f16061c2e093dc24ecc025eebf0950 # timeout=10<br/>Commit message: "Fix the Jenkins buildchain (#376)"<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] timestamps<br/>[Pipeline] {<br/>[Pipeline] timeout<br/>[2022-02-01T09:03:30.981Z] Timeout set to expire in 3 hr 0 min<br/>[Pipeline] {<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Tool Install)<br/>[Pipeline] tool<br/>[2022-02-01T09:03:31.160Z] Unpacking https://nodejs.org/dist/v12.16.3/node-v12.16.3-linux-x64.tar.gz to /home/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/nodejs-12.16.3 on rhos-d-kie-rhel7-xlarge-196<br/>[Pipeline] envVarsForTool<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] stage<br/>[Pipeline] { (Initialize)<br/>[Pipeline] tool<br/>[Pipeline] envVarsForTool<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>[2022-02-01T09:03:35.141Z] + printenv<br/>[Pipeline] archiveArtifacts<br/>[2022-02-01T09:03:35.217Z] Archiving artifacts<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // withEnv<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (check space before build)<br/>[Pipeline] tool<br/>[Pipeline] envVarsForTool<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] dir<br/>[2022-02-01T09:03:35.886Z] Running in /home/jenkins/workspace/KIE/kogito/1.11.x/pullrequest/optaplanner-quickstarts.tests.optaplanner-quickstarts<br/>[Pipeline] {<br/>[Pipeline] echo<br/>[2022-02-01T09:03:35.914Z] [INFO] space left on the machine<br/>[Pipeline] sh<br/>[2022-02-01T09:03:36.198Z] + df -h<br/>[2022-02-01T09:03:36.198Z] Filesystem      Size  Used Avail Use% Mounted on<br/>[2022-02-01T09:03:36.198Z] devtmpfs        7.8G     0  7.8G   0% /dev<br/>[2022-02-01T09:03:36.198Z] tmpfs           7.8G     0  7.8G   0% /dev/shm<br/>[2022-02-01T09:03:36.198Z] tmpfs           7.8G   17M  7.8G   1% /run<br/>[2022-02-01T09:03:36.198Z] tmpfs           7.8G     0  7.8G   0% /sys/fs/cgroup<br/>[2022-02-01T09:03:36.198Z] /dev/vda1        60G   18G   43G  30% /<br/>[2022-02-01T09:03:36.198Z] tmpfs           1.6G     0  1.6G   0% /run/user/0<br/>[2022-02-01T09:03:36.198Z] tmpfs           1.6G     0  1.6G   0% /run/user/1000<br/>[Pipeline] echo<br/>[2022-02-01T09:03:36.217Z] [INFO] space of /home/jenkins<br/>[Pipeline] sh<br/>[2022-02-01T09:03:36.499Z] + du -h -d1 /home/jenkins<br/>[2022-02-01T09:03:36.499Z] 4.0K	/home/jenkins/.ssh<br/>[2022-02-01T09:03:36.499Z] 0	/home/jenkins/go<br/>[2022-02-01T09:03:36.499Z] 8.0K	/home/jenkins/.vnc<br/>[2022-02-01T09:03:36.499Z] 8.0K	/home/jenkins/.m2<br/>[2022-02-01T09:03:36.786Z] 2.1G	/home/jenkins/git-repos<br/>[2022-02-01T09:03:36.786Z] 8.0K	/home/jenkins/.config<br/>[2022-02-01T09:03:36.786Z] 4.0K	/home/jenkins/.cekit<br/>[2022-02-01T09:03:37.377Z] 76M	/home/jenkins/virtenvs<br/>[2022-02-01T09:03:37.377Z] 30M	/home/jenkins/remoting<br/>[2022-02-01T09:03:37.377Z] 0	/home/jenkins/.cache<br/>[2022-02-01T09:03:37.377Z] 2.0M	/home/jenkins/workspace<br/>[2022-02-01T09:03:37.377Z] 0	/home/jenkins/.pki<br/>[2022-02-01T09:03:37.377Z] 81M	/home/jenkins/tools<br/>[2022-02-01T09:03:37.377Z] 0	/home/jenkins/caches<br/>[2022-02-01T09:03:37.377Z] 2.3G	/home/jenkins<br/>[Pipeline] echo<br/>[2022-02-01T09:03:37.396Z] [INFO] space of workspace<br/>[Pipeline] sh<br/>[2022-02-01T09:03:37.683Z] + du -h -d3 /home/jenkins/workspace<br/>[2022-02-01T09:03:37.683Z] 2.0M	/home/jenkins/workspace/KIE/kogito/1.11.x<br/>[2022-02-01T09:03:37.683Z] 2.0M	/home/jenkins/workspace/KIE/kogito<br/>[2022-02-01T09:03:37.683Z] 2.0M	/home/jenkins/workspace/KIE<br/>[2022-02-01T09:03:37.683Z] 2.0M	/home/jenkins/workspace<br/>[Pipeline] }<br/>[Pipeline] // dir<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // withEnv<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Build projects)<br/>[Pipeline] tool<br/>[Pipeline] envVarsForTool<br/>[Pipeline] tool<br/>[Pipeline] envVarsForTool<br/>[Pipeline] tool<br/>[Pipeline] envVarsForTool<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] configFileProvider<br/>[2022-02-01T09:03:38.154Z] provisioning config files...<br/>[2022-02-01T09:03:38.163Z] copy managed file [kogito_pr_settings] to file:/home/jenkins/workspace/KIE/kogito/1.11.x/pullrequest/optaplanner-quickstarts.tests.optaplanner-quickstarts@tmp/config3712140158918851022tmp<br/>[Pipeline] {<br/>[Pipeline] withCredentials<br/>[2022-02-01T09:03:38.219Z] Masking supported pattern matches of $GITHUB_TOKEN<br/>[Pipeline] {<br/>[Pipeline] sh<br/>[2022-02-01T09:03:38.248Z] Warning: A secret was passed to "sh" using Groovy String interpolation, which is insecure.<br/>[2022-02-01T09:03:38.248Z] 		 Affected argument(s) used the following variable(s): [GITHUB_TOKEN]<br/>[2022-02-01T09:03:38.248Z] 		 See https://jenkins.io/redirect/groovy-string-interpolation for details.<br/>[2022-02-01T09:03:38.568Z] + build-chain-action -token=**** '-df=https://raw.githubusercontent.com/${GROUP}/kogito-pipelines/1.11.x/.ci/pull-request-config.yaml' -folder=bc build pr -url=https://github.com/kiegroup/optaplanner-quickstarts/pull/273 -sp=kiegroup/optaplanner-quickstarts --skipParallelCheckout -cct '(^mvn .*)||$1 -s /home/jenkins/workspace/KIE/kogito/1.11.x/pullrequest/optaplanner-quickstarts.tests.optaplanner-quickstarts@tmp/config3712140158918851022tmp -Dmaven.wagon.http.ssl.insecure=true'<br/>[2022-02-01T09:03:38.568Z] /home/jenkins/workspace/KIE/kogito/1.11.x/pullrequest/optaplanner-quickstarts.tests.optaplanner-quickstarts@tmp/durable-19e157c9/script.sh: line 1: build-chain-action: command not found<br/>[Pipeline] }<br/>[Pipeline] // withCredentials<br/>[Pipeline] }<br/>[2022-02-01T09:03:38.625Z] Deleting 1 temporary files<br/>[Pipeline] // configFileProvider<br/>[Pipeline] }<br/>[Pipeline] // script<br/>Post stage<br/>[Pipeline] junit<br/>[2022-02-01T09:03:38.732Z] Recording test results<br/>[2022-02-01T09:03:38.848Z] No test report files were found. Configuration error?<br/>Error when executing always post condition:<br/>Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to rhos-d-kie-rhel7-xlarge-196<br/>		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1797)<br/>		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:356)<br/>		at hudson.remoting.Channel.call(Channel.java:1001)<br/>		at hudson.FilePath.act(FilePath.java:1166)<br/>		at hudson.FilePath.act(FilePath.java:1155)<br/>		at hudson.tasks.junit.JUnitParser.parseResult(JUnitParser.java:107)<br/>		at hudson.tasks.junit.JUnitResultArchiver.parse(JUnitResultArchiver.java:153)<br/>		at hudson.tasks.junit.JUnitResultArchiver.parseAndSummarize(JUnitResultArchiver.java:247)<br/>		at hudson.tasks.junit.pipeline.JUnitResultsStepExecution.run(JUnitResultsStepExecution.java:63)<br/>		at hudson.tasks.junit.pipeline.JUnitResultsStepExecution.run(JUnitResultsStepExecution.java:29)<br/>		at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)<br/>		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)<br/>hudson.AbortException: No test report files were found. Configuration error?<br/>	at hudson.tasks.junit.JUnitParser$ParseResultCallable.invoke(JUnitParser.java:154)<br/>	at hudson.FilePath$FileCallableWrapper.call(FilePath.java:3338)<br/>	at hudson.remoting.UserRequest.perform(UserRequest.java:211)<br/>	at hudson.remoting.UserRequest.perform(UserRequest.java:54)<br/>	at hudson.remoting.Request$2.run(Request.java:376)<br/>	at hudson.remoting.InterceptingExecutorService.lambda$wrap$0(InterceptingExecutorService.java:78)<br/>	at java.util.concurrent.FutureTask.run(FutureTask.java:266)<br/>	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)<br/>	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)<br/>	at java.lang.Thread.run(Thread.java:748)<br/><br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>[2022-02-01T09:03:39.176Z] + rm -rf console.log<br/>[Pipeline] sh<br/>
</details>

**Comment by rsynek** [comment]
jenkins retest this

**Comment by rsynek** [comment]
Build Chain does not work with the release branches correctly. Jenkins is green => merging.

**Pull request merged**
