### PR TITLE
BXMSPROD-1255 CI flows

### PR DESCRIPTION
**Pull request by Ginxo**
### JIRA
https://issues.redhat.com/browse/BXMSPROD-1255

### Referenced pull requests

- https://github.com/kiegroup/optaplanner-quickstarts/pull/81
- https://github.com/kiegroup/optaplanner-quickstarts/pull/82.
- https://github.com/kiegroup/optaplanner-quickstarts/pull/86

### CODE REVIEW

**Comment by mareknovotny** [comment]
again @ge0ffrey @triceo @rsynek please review

**Review by mareknovotny — APPROVED** [review]

**Review by antncl — APPROVED** [review]

**Review by rsynek — COMMENTED** [review]
Please see the suggestions in https://github.com/kiegroup/optaplanner-quickstarts/pull/81, as they apply here too.

I don't see a PR to the `development` branch, is there a plan to prepare one?

**Comment by Ginxo** [comment]
@rsynek waiting for clarification on https://github.com/kiegroup/optaplanner-quickstarts/pull/81#discussion_r599248249 to apply the same approach here.
About `development` branch... do we use `master` branch from optaplanner?
thanks man!

**Comment by rsynek** [comment]
> @rsynek waiting for clarification on [#81 (comment)](https://github.com/kiegroup/optaplanner-quickstarts/pull/81#discussion_r599248249) to apply the same approach here.
> About `development` branch... do we use `master` branch from optaplanner?
> thanks man!

yes, the `development` branch here maps to the `master` branch of optaplanner repo.

**Review by mareknovotny — APPROVED** [review]

**Comment by rsynek** [comment]
Let's finish the comments on the #81 first.

**Review by rsynek — APPROVED** [review]

**Pull request merged**
