### PR TITLE
KOGITO-6130 Upgrade to Quarkus 2.4.2

### PR DESCRIPTION
**Pull request by cristianonicolai**
Assembly:
- https://github.com/kiegroup/kogito-runtimes/pull/1695
- https://github.com/kiegroup/kogito-apps/pull/1095
- https://github.com/kiegroup/kogito-examples/pull/940
- https://github.com/kiegroup/optaplanner/pull/1658
- https://github.com/kiegroup/optaplanner-quickstarts/pull/220

### CODE REVIEW

**Comment by ge0ffrey** [comment]
ki-ci seems to have proposed a similar PR: https://github.com/kiegroup/optaplanner-quickstarts/pull/222

Your call on which you want to merge, just close the other one please :)

**Review by ge0ffrey — CHANGES_REQUESTED** [review]
Thanks for submitting.

This lacks changes for the gradle file:
  use-cases/school-timetabling/build.gradle
See the generated quarkus upgrade PRs that duplicate this PR.

**Comment by ge0ffrey** [comment]
Duplicate PRs:
  https://github.com/kiegroup/optaplanner-quickstarts/pull/222 (upgrade to 2.4.2 which is approved, it does the gradle file too)
  https://github.com/kiegroup/optaplanner-quickstarts/pull/221

**Comment by radtriste** [comment]
@cristianonicolai Could you integrate changes form https://github.com/kiegroup/optaplanner-quickstarts/pull/222 in there and close it ?

**Comment by cristianonicolai** [comment]
@ge0ffrey @radtriste done, update PR including the gradle changes

**Review by ge0ffrey — APPROVED** [review]
Thanks Christiano!

**Review by radtriste — APPROVED** [review]

**Pull request merged**
