### PR TITLE
bumped up to next 8.20.0-SNAPSHOT

### PR DESCRIPTION
**Pull request by mbiarnes**
- https://github.com/kiegroup/optaplanner/pull/1907
- https://github.com/kiegroup/optaplanner/pull/1907
- https://github.com/kiegroup/optaplanner-quickstarts/pull/316
- https://github.com/kiegroup/optaweb-employee-rostering/pull/784
- https://github.com/kiegroup/optaweb-vehicle-routing/pull/674
- https://github.com/kiegroup/kogito-apps/pull/1291
- https://github.com/kiegroup/kogito-examples/pull/1205
- https://github.com/kiegroup/kogito-runtimes/pull/2121)

### Referenced pull requests

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* for a <b>pull request build</b> please add comment: <b>Jenkins retest this</b>
* for a <b>full downstream build</b> please add the label `run_fdb`
* for a <b>specific pull request build</b> please add comment: <b>Jenkins (re)run [optaplanner-quickstarts] tests</b>
* for a <b>Quarkus LTS check</b> please add comment: <b>Jenkins run LTS</b>
* for a <b>specific Quarkus LTS check</b> please add comment: <b>Jenkins (re)run [optaplanner-quickstarts] LTS</b>
* for a <b>Native check</b> please add comment: <b>Jenkins run native</b>
* for a <b>specific Native LTS check</b> please add comment: <b>Jenkins (re)run [optaplanner-quickstarts] native</b>
</details>

### CI Status

You can check OptaPlanner repositories CI status from [Chain Status webpage](https://kiegroup.github.io/optaplanner/).

### CODE REVIEW

**Comment by kie-ci1** [comment]
**(tests) - optaplanner-quickstarts job** `#126` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/optaplanner-quickstarts.tests.optaplanner-quickstarts/126/display/redirect or see console log:
<details>
<summary><b>Console Logs</b></summary>
[INFO] Currently running in a labeled security context<br/> > /usr/bin/chcon --type=ssh_home_t /tmp/jenkins-gitclient-ssh9212511336541670764.key<br/> > git ls-remote -h https://github.com/kiegroup/jenkins-pipeline-shared-libraries # timeout=10<br/>Found match: refs/heads/main revision 474a1557998c4900619acee02a23d5a9a2e468bc<br/>The recommended git tool is: NONE<br/>using credential kie-ci-user-key<br/> > git rev-parse --resolve-git-dir /var/lib/jenkins/jobs/KIE/jobs/kogito/jobs/main/jobs/pullrequest/jobs/optaplanner-quickstarts.tests.optaplanner-quickstarts/workspace@libs/jenkins-pipeline-shared-libraries/.git # timeout=10<br/>Fetching changes from the remote Git repository<br/> > git config remote.origin.url https://github.com/kiegroup/jenkins-pipeline-shared-libraries # timeout=10<br/>Fetching without tags<br/>Fetching upstream changes from https://github.com/kiegroup/jenkins-pipeline-shared-libraries<br/> > git --version # timeout=10<br/> > git --version # 'git version 1.8.3.1'<br/>using GIT_SSH to set credentials SSH: kie-ci service account with access to jboss-integration private github space<br/>[INFO] Currently running in a labeled security context<br/> > /usr/bin/chcon --type=ssh_home_t /var/lib/jenkins/jobs/KIE/jobs/kogito/jobs/main/jobs/pullrequest/jobs/optaplanner-quickstarts.tests.optaplanner-quickstarts/workspace@libs/jenkins-pipeline-shared-libraries@tmp/jenkins-gitclient-ssh3426499203774785571.key<br/> > git fetch --no-tags --progress https://github.com/kiegroup/jenkins-pipeline-shared-libraries +refs/heads/*:refs/remotes/origin/* # timeout=10<br/>Checking out Revision 474a1557998c4900619acee02a23d5a9a2e468bc (main)<br/> > git config core.sparsecheckout # timeout=10<br/> > git checkout -f 474a1557998c4900619acee02a23d5a9a2e468bc # timeout=10<br/>Commit message: "Do not turn build number into a GH issue/PR link (#187)"<br/> > git rev-list --no-walk 474a1557998c4900619acee02a23d5a9a2e468bc # timeout=10<br/>[Pipeline] Start of Pipeline<br/>[Pipeline] node<br/>Still waiting to schedule task<br/>Waiting for next available executor on ‘kie-rhel7&&kie-mem16g&&!master’<br/>Running on rhos-01-kie-psi-rhel7-xlarge-113 in /home/jenkins/workspace/KIE/kogito/main/pullrequest/optaplanner-quickstarts.tests.optaplanner-quickstarts<br/>[Pipeline] {<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Checkout SCM)<br/>[Pipeline] checkout<br/>The recommended git tool is: NONE<br/>using credential kie-ci<br/>Cloning the remote Git repository<br/>Avoid second fetch<br/>Checking out Revision c1753a782d3640e702a77a121ce99cec623ab6d3 (origin/main)<br/>Cloning repository https://github.com/kiegroup/kogito-pipelines.git<br/> > git init /home/jenkins/workspace/KIE/kogito/main/pullrequest/optaplanner-quickstarts.tests.optaplanner-quickstarts # timeout=10<br/>Fetching upstream changes from https://github.com/kiegroup/kogito-pipelines.git<br/> > git --version # timeout=10<br/> > git --version # 'git version 2.34.1'<br/>using GIT_ASKPASS to set credentials PSSWD: kie-ci service account with access to jboss-integration private github space<br/> > git fetch --tags --force --progress -- https://github.com/kiegroup/kogito-pipelines.git +refs/heads/*:refs/remotes/origin/* # timeout=10<br/> > git config remote.origin.url https://github.com/kiegroup/kogito-pipelines.git # timeout=10<br/> > git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10<br/> > git rev-parse origin/main^{commit} # timeout=10<br/> > git config core.sparsecheckout # timeout=10<br/> > git checkout -f c1753a782d3640e702a77a121ce99cec623ab6d3 # timeout=10<br/>Commit message: "BXMSPROD-1671 kogito-nightly-main removed (#408)"<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] timestamps<br/>[Pipeline] {<br/>[Pipeline] timeout<br/>[2022-04-01T15:34:01.620Z] Timeout set to expire in 3 hr 0 min<br/>[Pipeline] {<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Tool Install)<br/>[Pipeline] tool<br/>[2022-04-01T15:34:01.805Z] Unpacking https://nodejs.org/dist/v12.16.3/node-v12.16.3-linux-x64.tar.gz to /home/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/nodejs-12.16.3 on rhos-01-kie-psi-rhel7-xlarge-113<br/>[Pipeline] envVarsForTool<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] stage<br/>[Pipeline] { (Initialize)<br/>[Pipeline] tool<br/>[Pipeline] envVarsForTool<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>[2022-04-01T15:34:04.800Z] + printenv<br/>[Pipeline] archiveArtifacts<br/>[2022-04-01T15:34:04.906Z] Archiving artifacts<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // withEnv<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (check space before build)<br/>[Pipeline] tool<br/>[Pipeline] envVarsForTool<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] dir<br/>[2022-04-01T15:34:05.597Z] Running in /home/jenkins/workspace/KIE/kogito/main/pullrequest/optaplanner-quickstarts.tests.optaplanner-quickstarts<br/>[Pipeline] {<br/>[Pipeline] echo<br/>[2022-04-01T15:34:05.644Z] [INFO] space left on the machine<br/>[Pipeline] sh<br/>[2022-04-01T15:34:05.926Z] + df -h<br/>[2022-04-01T15:34:05.926Z] Filesystem      Size  Used Avail Use% Mounted on<br/>[2022-04-01T15:34:05.926Z] devtmpfs        7.8G     0  7.8G   0% /dev<br/>[2022-04-01T15:34:05.926Z] tmpfs           7.8G     0  7.8G   0% /dev/shm<br/>[2022-04-01T15:34:05.926Z] tmpfs           7.8G   17M  7.8G   1% /run<br/>[2022-04-01T15:34:05.926Z] tmpfs           7.8G     0  7.8G   0% /sys/fs/cgroup<br/>[2022-04-01T15:34:05.926Z] /dev/vda1        80G   18G   63G  23% /<br/>[2022-04-01T15:34:05.926Z] tmpfs           1.6G     0  1.6G   0% /run/user/1000<br/>[Pipeline] echo<br/>[2022-04-01T15:34:05.944Z] [INFO] space of /home/jenkins<br/>[Pipeline] sh<br/>[2022-04-01T15:34:06.224Z] + du -h -d1 /home/jenkins<br/>[2022-04-01T15:34:06.224Z] 4.0K	/home/jenkins/.ssh<br/>[2022-04-01T15:34:06.224Z] 0	/home/jenkins/go<br/>[2022-04-01T15:34:06.224Z] 8.0K	/home/jenkins/.vnc<br/>[2022-04-01T15:34:06.224Z] 8.0K	/home/jenkins/.m2<br/>[2022-04-01T15:34:06.224Z] 2.1G	/home/jenkins/git-repos<br/>[2022-04-01T15:34:06.224Z] 8.0K	/home/jenkins/.config<br/>[2022-04-01T15:34:06.224Z] 4.0K	/home/jenkins/.cekit<br/>[2022-04-01T15:34:06.224Z] 80M	/home/jenkins/virtenvs<br/>[2022-04-01T15:34:06.224Z] 30M	/home/jenkins/remoting<br/>[2022-04-01T15:34:06.224Z] 0	/home/jenkins/.cache<br/>[2022-04-01T15:34:06.224Z] 2.1M	/home/jenkins/workspace<br/>[2022-04-01T15:34:06.224Z] 0	/home/jenkins/.pki<br/>[2022-04-01T15:34:06.224Z] 81M	/home/jenkins/tools<br/>[2022-04-01T15:34:06.224Z] 0	/home/jenkins/caches<br/>[2022-04-01T15:34:06.224Z] 2.3G	/home/jenkins<br/>[Pipeline] echo<br/>[2022-04-01T15:34:06.243Z] [INFO] space of workspace<br/>[Pipeline] sh<br/>[2022-04-01T15:34:06.527Z] + du -h -d3 /home/jenkins/workspace<br/>[2022-04-01T15:34:06.528Z] 2.1M	/home/jenkins/workspace/KIE/kogito/main<br/>[2022-04-01T15:34:06.528Z] 2.1M	/home/jenkins/workspace/KIE/kogito<br/>[2022-04-01T15:34:06.528Z] 2.1M	/home/jenkins/workspace/KIE<br/>[2022-04-01T15:34:06.528Z] 2.1M	/home/jenkins/workspace<br/>[Pipeline] }<br/>[Pipeline] // dir<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // withEnv<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Install build-chain tool)<br/>[Pipeline] tool<br/>[Pipeline] envVarsForTool<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] echo<br/>[2022-04-01T15:34:06.892Z] [INFO] Getting build-chain version from composite action file<br/>[Pipeline] readFile<br/>[Pipeline] echo<br/>[2022-04-01T15:34:06.977Z] [INFO] build-chain version recovered '2.3.34'<br/>[Pipeline] sh<br/>[2022-04-01T15:34:07.264Z] + npm install -g @kie/build-chain-action@2.3.34 -registry=https://repository.engineering.redhat.com/nexus/repository/registry.npmjs.org/<br/>[2022-04-01T15:34:10.535Z] /home/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/nodejs-12.16.3/bin/build-chain-action -> /home/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/nodejs-12.16.3/lib/node_modules/@kie/build-chain-action/bin/build-chain-cli.js<br/>[2022-04-01T15:34:10.535Z] npm WARN notsup Unsupported engine for @kie/build-chain-action@2.3.34: wanted: {"node":">= 12.18.0"} (current: {"node":"12.16.3","npm":"6.14.4"})<br/>[2022-04-01T15:34:10.535Z] npm WARN notsup Not compatible with your version of node/npm: @kie/build-chain-action@2.3.34<br/>[2022-04-01T15:34:10.535Z] npm WARN @octokit/plugin-request-log@1.0.4 requires a peer of @octokit/core@>=3 but none is installed. You must install peer dependencies yourself.<br/>[2022-04-01T15:34:10.535Z] <br/>[2022-04-01T15:34:10.535Z] + @kie/build-chain-action@2.3.34<br/>[2022-04-01T15:34:10.535Z] added 110 packages from 88 contributors in 2.733s<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // withEnv<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Build projects)<br/>[Pipeline] tool<br/>[Pipeline] envVarsForTool<br/>[Pipeline] tool<br/>[Pipeline] envVarsForTool<br/>[Pipeline] tool<br/>[Pipeline] envVarsForTool<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] configFileProvider<br/>[2022-04-01T15:34:11.022Z] provisioning config files...<br/>[2022-04-01T15:34:11.029Z] copy managed file [kogito_pr_settings] to file:/home/jenkins/workspace/KIE/kogito/main/pullrequest/optaplanner-quickstarts.tests.optaplanner-quickstarts@tmp/config3683324976084067426tmp<br/>[Pipeline] {<br/>[Pipeline] withCredentials<br/>[2022-04-01T15:34:11.072Z] Masking supported pattern matches of $GITHUB_TOKEN<br/>[Pipeline] {<br/>[Pipeline] sh<br/>[2022-04-01T15:34:11.106Z] Warning: A secret was passed to "sh" using Groovy String interpolation, which is insecure.<br/>[2022-04-01T15:34:11.106Z] 		 Affected argument(s) used the following variable(s): [GITHUB_TOKEN]<br/>[2022-04-01T15:34:11.106Z] 		 See https://jenkins.io/redirect/groovy-string-interpolation for details.<br/>[2022-04-01T15:34:11.415Z] + build-chain-action -token=**** -df=https://raw.githubusercontent.com/kiegroup/kogito-pipelines/main/.ci/pull-request-config.yaml -folder=bc build pr -url=https://github.com/kiegroup/optaplanner-quickstarts/pull/316 -sp=kiegroup/optaplanner-quickstarts --skipParallelCheckout -cct '(^mvn .*)||$1 -s /home/jenkins/workspace/KIE/kogito/main/pullrequest/optaplanner-quickstarts.tests.optaplanner-quickstarts@tmp/config3683324976084067426tmp -Dmaven.wagon.http.ssl.insecure=true -Dmaven.test.failure.ignore=true'<br/>[2022-04-01T15:34:11.675Z] [INFO]  Executing pull request flow for https://github.com/kiegroup/optaplanner-quickstarts/pull/316 in bc<br/>[2022-04-01T15:34:11.932Z] [INFO]  https://raw.githubusercontent.com/kiegroup/kogito-pipelines/main/.ci/pull-request-config.yaml exists, using it<br/>[2022-04-01T15:34:11.932Z] ::group::[PRE] Executing pre section for https://raw.githubusercontent.com/kiegroup/kogito-pipelines/main/.ci/pull-request-config.yaml<br/>[2022-04-01T15:34:11.932Z] [INFO]  Execute command 'export BUILD_MVN_OPTS=" -nsu -ntp -fae -e -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false dependency:tree -Dmaven.wagon.httpconnectionManager.ttlSeconds=120 -Dmaven.wagon.http.retryHandler.count=3"' in dir '/home/jenkins/workspace/KIE/kogito/main/pullrequest/optaplanner-quickstarts.tests.optaplanner-quickstarts'<br/>[2022-04-01T15:34:11.932Z] [INFO]  Treating export command since it's not possible to run it from the runner itself<br/>[2022-04-01T15:34:11.932Z] [INFO]  The variable BUILD_MVN_OPTS has been stored with ' -nsu -ntp -fae -e -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false dependency:tree -Dmaven.wagon.httpconnectionManager.ttlSeconds=120 -Dmaven.wagon.http.retryHandler.count=3' value<br/>[2022-04-01T15:34:11.932Z] ::notice title= [PRE] [Execution OK]::export BUILD_MVN_OPTS=" -nsu -ntp -fae -e -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false dependency:tree -Dmaven.wagon.httpconnectionManager.ttlSeconds=120 -Dmaven.wagon.http.retryHandler.count=3"<br/>[2022-04-01T15:34:11.932Z] [INFO]  Execute command 'echo "BUILD_MVN_OPTS= -nsu -ntp -fae -e -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false dependency:tree -Dmaven.wagon.httpconnectionManager.ttlSeconds=120 -Dmaven.wagon.http.retryHandler.count=3"' in dir '/home/jenkins/workspace/KIE/kogito/main/pullrequest/optaplanner-quickstarts.tests.optaplanner-quickstarts'<br/>[2022-04-01T15:34:11.932Z] [command]/usr/bin/echo BUILD_MVN_OPTS= -nsu -ntp -fae -e -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false dependency:tree -Dmaven.wagon.httpconnectionManager.ttlSeconds=120 -Dmaven.wagon.http.retryHandler.count=3<br/>[2022-04-01T15:34:11.932Z] BUILD_MVN_OPTS= -nsu -ntp -fae -e -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false dependency:tree -Dmaven.wagon.httpconnectionManager.ttlSeconds=120 -Dmaven.wagon.http.retryHandler.count=3<br/>[2022-04-01T15:34:11.932Z] ::notice title= [PRE] [Execution OK]::echo "BUILD_MVN_OPTS= -nsu -ntp -fae -e -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false dependency:tree -Dmaven.wagon.httpconnectionManager.ttlSeconds=120 -Dmaven.wagon.http.retryHandler.count=3"<br/>[2022-04-01T15:34:11.932Z] ::endgroup::<br/>[2022-04-01T15:34:11.932Z] ::group::[Pull Request Flow] Execution Plan...<br/>[2022-04-01T15:34:11.932Z] [INFO]  ----------------------------------------------<br/>[2022-04-01T15:34:11.932Z] [INFO]  [3] projects will be executed<br/>[2022-04-01T15:34:11.932Z] <br/>[2022-04-01T15:34:11.932Z] [INFO]  [kiegroup/drools]<br/>[2022-04-01T15:34:11.932Z] [INFO]  Level Type: [upstream].<br/>[2022-04-01T15:34:11.932Z] [INFO]  mvn clean install -Dquickly ${{ env.BUILD_MVN_OPTS }} ${{ env.BUILD_MVN_OPTS_UPSTREAM }} ${{ env.DROOLS_BUILD_MVN_OPTS_UPSTREAM }}<br/>[2022-04-01T15:34:11.932Z] [INFO]  [ [32m'docker system prune -f'[39m ]<br/>[2022-04-01T15:34:11.932Z] <br/>[2022-04-01T15:34:11.932Z] [INFO]  [kiegroup/optaplanner]<br/>[2022-04-01T15:34:11.932Z] [INFO]  Level Type: [upstream].<br/>[2022-04-01T15:34:11.932Z] [INFO]  mvn clean install -Dquickly ${{ env.BUILD_MVN_OPTS }} ${{ env.BUILD_MVN_OPTS_UPSTREAM }} ${{ env.OPTAPLANNER_BUILD_MVN_OPTS_UPSTREAM }}<br/>[2022-04-01T15:34:11.932Z] [INFO]  [ [32m'docker system prune -f'[39m ]<br/>[2022-04-01T15:34:11.932Z] <br/>[2022-04-01T15:34:11.932Z] [INFO]  [kiegroup/optaplanner-quickstarts]<br/>[2022-04-01T15:34:11.932Z] [INFO]  Level Type: [current].<br/>[2022-04-01T15:34:11.932Z] [INFO]  mvn clean install -f optaplanner-quickstarts/pom.xml ${{ env.BUILD_MVN_OPTS }} ${{ env.BUILD_MVN_OPTS_CURRENT }} ${{ env.OPTAPLANNER_QUICKSTARTS_BUILD_MVN_OPTS }}<br/>[2022-04-01T15:34:11.932Z] [INFO]  [ [32m'docker system prune -f'[39m ]<br/>[2022-04-01T15:34:11.932Z] <br/>[2022-04-01T15:34:11.932Z] [INFO]  ----------------------------------------------<br/>[2022-04-01T15:34:11.932Z] ::endgroup::<br/>[2022-04-01T15:34:11.932Z] ::group::[Pull Request Flow] Checking out kiegroup/optaplanner-quickstarts and its dependencies<br/>[2022-04-01T15:34:11.932Z] [INFO]  Tree for project kiegroup/optaplanner-quickstarts. Dependencies: <br/>[2022-04-01T15:34:11.932Z] kiegroup/drools,<br/>[2022-04-01T15:34:11.932Z] kiegroup/optaplanner,<br/>[2022-04-01T15:34:11.932Z] kiegroup/optaplanner-quickstarts<br/>[2022-04-01T15:34:11.932Z] [INFO]  [kiegroup/drools] Checking out project<br/>[2022-04-01T15:34:12.494Z] [WARN]  project github.com/kiegroup/drools:bump-up does not exist. It's not necessarily an error.<br/>[2022-04-01T15:34:12.494Z] [INFO]  [kiegroup/drools] Checking out 'https://github.com/kiegroup/drools:main' into 'bc/kiegroup_drools'<br/>[2022-04-01T15:34:30.536Z] [INFO]  [kiegroup/drools] Checked out.<br/>[2022-04-01T15:34:30.536Z] [INFO]  [kiegroup/drools] Cloning folder bc/kiegroup_drools into drools<br/>[2022-04-01T15:34:31.464Z] [INFO]  [kiegroup/drools] Cloned folder bc/kiegroup_drools into bc/kiegroup_drools/drools<br/>[2022-04-01T15:34:31.464Z] [INFO]  [kiegroup/optaplanner] Checking out project<br/>[2022-04-01T15:34:31.720Z] [INFO]  [kiegroup/optaplanner] Merging https://github.com/kiegroup/optaplanner:main into https://github.com/mbiarnes/optaplanner:bump-up<br/>[2022-04-01T15:34:49.760Z] [INFO]  [kiegroup/optaplanner] Checked out.<br/>[2022-04-01T15:34:49.760Z] [INFO]  [kiegroup/optaplanner] Cloning folder bc/kiegroup_optaplanner into optaplanner<br/>[2022-04-01T15:34:49.760Z] [INFO]  [kiegroup/optaplanner] Cloned folder bc/kiegroup_optaplanner into bc/kiegroup_optaplanner/optaplanner<br/>[2022-04-01T15:34:49.760Z] [INFO]  [kiegroup/optaplanner-quickstarts] Checking out project<br/>[2022-04-01T15:34:50.016Z] [INFO]  [kiegroup/optaplanner-quickstarts] Merging https://github.com/kiegroup/optaplanner-quickstarts:development into https://github.com/mbiarnes/optaplanner-quickstarts:bump-up<br/>[2022-04-01T15:34:51.381Z] [ERROR]  command git pull --no-rebase https://****@github.com/mbiarnes/optaplanner-quickstarts bump-up failed with code 1. Error Message: From https://github.com/mbiarnes/optaplanner-quickstarts<br/>[2022-04-01T15:34:51.381Z]  * branch            bump-up    -> FETCH_HEAD<br/>[2022-04-01T15:34:51.381Z] Auto-merging technology/java-spring-boot/build.gradle<br/>[2022-04-01T15:34:51.381Z] Auto-merging technology/java-spring-boot/pom.xml<br/>[2022-04-01T15:34:51.381Z] CONFLICT (content): Merge conflict in technology/java-spring-boot/pom.xml<br/>[2022-04-01T15:34:51.381Z] Automatic merge failed; fix conflicts and then commit the result.<br/>[2022-04-01T15:34:51.381Z] <br/>[Pipeline] }<br/>[Pipeline] // withCredentials<br/>[Pipeline] }<br/>[2022-04-01T15:34:51.447Z] Deleting 1 temporary files<br/>[Pipeline] // configFileProvider<br/>[Pipeline] }<br/>[Pipeline] // script<br/>Post stage<br/>[Pipeline] junit<br/>[2022-04-01T15:34:51.588Z] Recording test results<br/>[2022-04-01T15:34:52.212Z] No test report files were found. Configuration error?<br/>Error when executing always post condition:<br/>Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to rhos-01-kie-psi-rhel7-xlarge-113<br/>		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1797)<br/>		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:356)<br/>		at hudson.remoting.Channel.call(Channel.java:1001)<br/>		at hudson.FilePath.act(FilePath.java:1166)<br/>		at hudson.FilePath.act(FilePath.java:1155)<br/>		at hudson.tasks.junit.JUnitParser.parseResult(JUnitParser.java:107)<br/>		at hudson.tasks.junit.JUnitResultArchiver.parse(JUnitResultArchiver.java:153)<br/>		at hudson.tasks.junit.JUnitResultArchiver.parseAndSummarize(JUnitResultArchiver.java:247)<br/>		at hudson.tasks.junit.pipeline.JUnitResultsStepExecution.run(JUnitResultsStepExecution.java:63)<br/>		at hudson.tasks.junit.pipeline.JUnitResultsStepExecution.run(JUnitResultsStepExecution.java:29)<br/>		at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)<br/>		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)<br/>		at java.util.concurrent.FutureTask.run(FutureTask.java:266)<br/>		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)<br/>		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)<br/>		at java.lang.Thread.run(Thread.java:748)<br/>hudson.AbortException: No test report files were found. Configuration error?<br/>	at hudson.tasks.junit.JUnitParser$ParseResultCallable.invoke(JUnitParser.java:154)<br/>	at hudson.FilePath$FileCallableWrapper.call(FilePath.java:3338)<br/>	at hudson.remoting.UserRequest.perform(UserRequest.java:211)<br/>	at hudson.remoting.UserRequest.perform(UserRequest.java:54)<br/>	at hudson.remoting.Request$2.run(Request.java:376)<br/>	at hudson.remoting.InterceptingExecutorService.lambda$wrap$0(InterceptingExecutorService.java:78)<br/>	at java.util.concurrent.FutureTask.run(FutureTask.java:266)<br/>	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)<br/>	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)<br/>	at java.lang.Thread.run(Thread.java:750)<br/><br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>[2022-04-01T15:34:52.530Z] + rm -rf console.log<br/>[Pipeline] sh<br/>
</details>

**Review by cristianonicolai — APPROVED** [review]

**Comment by mbiarnes** [comment]
Jenkins retest this

**Comment by dupliaka** [comment]
Jenkins retest this

**Review by triceo — APPROVED** [review]
Gradle CI will not be green until 8.20 SNAPSHOTs hit Nexus.

**Comment by dupliaka** [comment]
> Gradle CI will not be green until 8.20 SNAPSHOTs hit Nexus.
From this I got the impression that it is there https://repository.jboss.org/nexus/content/groups/public/org/optaplanner/optaplanner-bom/8.20.0-SNAPSHOT/

**Review by dupliaka — APPROVED** [review]

**Pull request merged**
