### PR TITLE
BXMSPROD-1540 composite actions centralized github actions

### PR DESCRIPTION
**Pull request by Ginxo**
### JIRA

https://issues.redhat.com/browse/BXMSPROD-1540

### Referenced pull requests

* https://github.com/kiegroup/kogito-pipelines/pull/313

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* for a <b>pull request build</b> please add comment: <b>Jenkins retest this</b>
* for a <b>full downstream build</b> please add the label `run_fdb`
* for a <b>specific pull request build</b> please add comment: <b>Jenkins (re)run [optaplanner-quickstarts] tests</b>
* for a <b>Quarkus LTS check</b> please add comment: <b>Jenkins run LTS</b>
* for a <b>specific Quarkus LTS check</b> please add comment: <b>Jenkins (re)run [optaplanner-quickstarts] LTS</b>
* for a <b>Native check</b> please add comment: <b>Jenkins run native</b>
* for a <b>specific Native LTS check</b> please add comment: <b>Jenkins (re)run [optaplanner-quickstarts] native</b>
</details>

### CODE REVIEW

**Review by triceo — APPROVED** [review]

**Comment by Ginxo** [comment]
it will obviously not work until https://github.com/kiegroup/kogito-pipelines/pull/313 is merged

**Comment by triceo** [comment]
@Ginxo Mind rebasing? I'd like to merge this one.

**Comment by rsynek** [comment]
@Ginxo is this PR still relevant?

**Comment by Ginxo** [comment]
out of date. Closing

**Pull request closed without merging**
