### PR TITLE
PLANNER-2892 Update default Maven to 3.8.7

### PR DESCRIPTION
**Pull request by radtriste**
https://issues.redhat.com/browse/PLANNER-2892

Related:
- https://github.com/kiegroup/optaplanner/pull/2530
- https://github.com/kiegroup/optaweb-vehicle-routing/pull/840
- https://github.com/kiegroup/optaplanner-quickstarts/pull/497

### CODE REVIEW

**Review by triceo — APPROVED** [review]

**Comment by radtriste** [comment]
@triceo https://github.com/kiegroup/optaplanner-quickstarts/pull/495 was merged with a lot of jobs failing
This is due to the setup-java update which requires to setup a `distribution` field ...

**Comment by radtriste** [comment]
in kogito-pipelines, we use `temurin` -> https://github.com/kiegroup/kogito-pipelines/blob/main/.ci/actions/maven/action.yml#L30

**Comment by radtriste** [comment]
should I update ? :)

**Comment by radtriste** [comment]
@triceo updated

**Comment by triceo** [comment]
Crap. :-( Thanks @radtriste, I don't know how I missed that.

**Pull request merged**
