### PR TITLE
[development] nightly GHA job

### PR DESCRIPTION
**Pull request by Ginxo**
https://github.com/kiegroup/optaplanner-quickstarts/pull/265 backported to development just to keep stable/development aligned

### CODE REVIEW

**Comment by rsynek** [comment]
I am thinking if we actually need it for the `development` branch. The main goal was to make sure that what users get has not been broken during the release. Users get the `stable` (default) branch.

**Comment by Ginxo** [comment]
@rsynek we don't need it, and this file won't affect on anything apart from being aligned with the things from `stable` branch. Only default branch flows are taken into consideration by GHA (apart from the ones from PR's source branch, but this is not the case)

**Comment by rsynek** [comment]
Actually, we need this file, because otherwise, the `development` branch would override it on the `stable` branch during the release (`stable` is reset to the last commit of the release branch).

**Review by rsynek — APPROVED** [review]

**Comment by Ginxo** [comment]
> Actually, we need this file, because otherwise, the `development` branch would override it on the `stable` branch during the release (`stable` is reset to the last commit of the release branch).

That's what I meant, sorry if I didn't explain myself well. Thanks

**Pull request merged**
