### PR TITLE
KOGITO-5783 Specific env for Optaplanner upstream

### PR DESCRIPTION
**Pull request by radtriste**
### JIRA

https://issues.redhat.com/browse/KOGITO-5783

### Referenced pull requests

https://github.com/kiegroup/kogito-apps/pull/1033
https://github.com/kiegroup/kogito-examples/pull/897
https://github.com/kiegroup/kogito-pipelines/pull/271
https://github.com/kiegroup/kogito-apps/pull/1049
https://github.com/kiegroup/optaplanner-quickstarts/pull/191

### CODE REVIEW

**Review by rsynek — APPROVED** [review]

**Comment by radtriste** [comment]
jenkins retest this

**Comment by radtriste** [comment]
jenkins retest this

**Comment by radtriste** [comment]
jenkins retest this

**Comment by radtriste** [comment]
jenkins retest this

**Pull request merged**
